# Site settings
title: Clay Carson's Book Note Archive
motto: Here is where I keep an archive of notes and quotes from books I have read.
email: me@claycarson.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: claycarson
github_username:  claycarson

# Build settings
markdown: kramdown
