# Permalinks
permalink: /:categories/:year/:month/:title

# Setup
title:               Clay Carson
tagline:             
url:                 http://claycarson.net
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Clay Carson
  url:               http://claycarson.me
  email:             clay@claycarson.net

# Custom vars
version:             2.0.0
github:
  repo:              https:claycarson.github.io
  
# Build settings
markdown: kramdown

# Extras
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
